version: '3.3'

services:

  wordpress:

    image: wordpress

    restart: always

    links:

      - wordpressdb-zhiharko:mysql

    ports:

      - "8080:80"

    working_dir: /var/www/html

    volumes:

      - "/opt/wp-content:/var/www/html/wp-content"

    environment:

      WORDPRESS_DB_HOST: wordpressdb-zhiharko:3306

      WORDPRESS_DB_USER: wordpress

      WORDPRESS_DB_PASSWORD: wordpress

      WORDPRESS_DB_NAME: wordpress

  

  joomla:

    image: joomla

    restart: always

    links:

      - wordpressdb-zhiharko:mysql

    ports:

      - 8080:80

    environment:

      JOOMLA_DB_HOST: wordpressdb-zhiharko:3306

      JOOMLA_DB_PASSWORD: wordpress

  

  wordpressdb-zhiharko:

      image: mariadb:latest

      restart: always

      volumes:

        - "/opt/mysql:/var/lib/mysql"

      environment:

        MYSQL_ROOT_PASSWORD: secret

        MYSQL_DATABASE: wordpress

        MYSQL_USER: wordpress

        MYSQL_PASSWORD: wordpress
